// example/vue/src/App.vue
<script setup lang="ts">
import "@thorvg/lottie-player";
</script>

<template>
  <div className="app">
    <h1 className="app_title">ThorVG Vue Usage Example</h1>
    <lottie-player
      autoplay
      loop
      intermission="1000"
      mode="normal"
      src="https://lottie.host/6d7dd6e2-ab92-4e98-826a-2f8430768886/NGnHQ6brWA.json"
      style="width: 500px; height: 500px"></lottie-player>
  </div>
</template>

// example/react/src/App.tsx
import "@thorvg/lottie-player";
import "./styles.css";

const App = () => {
  return (
    <div className="app">
      <h1 className="app_title">ThorVG React Usage Example</h1>
      <lottie-player
        autoPlay
        loop
        mode="normal"
        src="https://lottie.host/6d7dd6e2-ab92-4e98-826a-2f8430768886/NGnHQ6brWA.json"
        style={{ width: 500, height: 500 }}
      />
    </div>
  );
};

export default App;
